from fpdf import FPDF
import datetime
import os

class CyberReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'CYBERCRIME INCIDENT REPORT', 0, 1, 'C')
        self.ln(5)
        self.line(10, 25, 200, 25) # Draw a line

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by Social Safegram - Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(data: dict, image_paths: list):
    """
    Generates a PDF with text and attached screenshots.
    """
    pdf = CyberReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. Incident Details
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. Incident Information", 0, 1)
    pdf.set_font("Arial", size=11)
    
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    info_text = (
        f"Report Generated On: {timestamp}\n"
        f"Incident Type: {data.get('type')}\n"
        f"Date of Incident: {data.get('date')}"
    )
    pdf.multi_cell(0, 7, info_text)
    pdf.ln(5)

    # 2. Victim Details
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "2. Victim Details", 0, 1)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, f"Name: {data.get('name')}\nContact: {data.get('contact')}")
    pdf.ln(5)

    # 3. Description
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "3. Description of Event", 0, 1)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, f"{data.get('description')}")
    pdf.ln(5)

    # 4. Evidence (Screenshots)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "4. Evidence & Screenshots", 0, 1)
    pdf.ln(2)

    if not image_paths:
        pdf.set_font("Arial", 'I', 11)
        pdf.cell(0, 10, "(No screenshots provided)", 0, 1)
    else:
        for img_path in image_paths:
            try:
                # Add image, width 100mm (centered roughly)
                pdf.image(img_path, w=150) 
                pdf.ln(5)
            except Exception as e:
                pdf.cell(0, 10, f"Error loading image: {str(e)}", 0, 1)

    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: This is an automated draft. Please verify all details before submitting to official authorities.")

    # Return PDF as bytes (Safe method)
    return pdf.output(dest='S').encode('latin-1')